from __future__ import annotations

from datetime import date

from app.schemas.api import DemoUserSummary
from app.schemas.domain import AbsenceRecord, Employee

MOCK_EMPLOYEES: list[Employee] = [
    Employee(
        employee_id="E1000",
        display_name="Meryem Ait Said",
        first_name="Meryem",
        last_name="Ait Said",
        email="meryem.aitsaid@example.local",
        aliases=["Meryem"],
    ),
    Employee(
        employee_id="E1001",
        display_name="Sara Bennani",
        first_name="Sara",
        last_name="Bennani",
        email="sara.bennani@example.local",
        manager_employee_id="E1000",
        aliases=["Sara", "Sara B."],
    ),
    Employee(
        employee_id="E1002",
        display_name="Ahmed El Idrissi",
        first_name="Ahmed",
        last_name="El Idrissi",
        email="ahmed.elidrissi@example.local",
        manager_employee_id="E1000",
        aliases=["Ahmed"],
    ),
    Employee(
        employee_id="E1003",
        display_name="Yasmine Alami",
        first_name="Yasmine",
        last_name="Alami",
        email="yasmine.alami@example.local",
        manager_employee_id="E1000",
        aliases=["Yasmine"],
    ),
    Employee(
        employee_id="E1004",
        display_name="Omar Kabbaj",
        first_name="Omar",
        last_name="Kabbaj",
        email="omar.kabbaj@example.local",
        aliases=["Omar"],
    ),
    Employee(
        employee_id="E1005",
        display_name="Karim Ouali",
        first_name="Karim",
        last_name="Ouali",
        email="karim.ouali@example.local",
        manager_employee_id="E1004",
        aliases=["Karim"],
    ),
    Employee(
        employee_id="E1006",
        display_name="Yasmine Amrani",
        first_name="Yasmine",
        last_name="Amrani",
        email="yasmine.amrani@example.local",
        manager_employee_id="E1004",
        aliases=["Yasmine"],
    ),
    Employee(
        employee_id="E9000",
        display_name="Nadia El Fassi",
        first_name="Nadia",
        last_name="El Fassi",
        email="nadia.elfassi@example.local",
        aliases=["Nadia"],
    ),
]

MOCK_ABSENCES: list[AbsenceRecord] = [
    AbsenceRecord(
        absence_id="ABS-001",
        employee_id="E1001",
        employee_display_name="Sara Bennani",
        absence_type="Sick Leave",
        start_date=date(2026, 1, 12),
        end_date=date(2026, 1, 12),
        days=1.0,
    ),
    AbsenceRecord(
        absence_id="ABS-002",
        employee_id="E1001",
        employee_display_name="Sara Bennani",
        absence_type="Annual Leave",
        start_date=date(2026, 2, 3),
        end_date=date(2026, 2, 5),
        days=3.0,
    ),
    AbsenceRecord(
        absence_id="ABS-003",
        employee_id="E1001",
        employee_display_name="Sara Bennani",
        absence_type="Sick Leave",
        start_date=date(2026, 3, 14),
        end_date=date(2026, 3, 14),
        days=1.0,
    ),
    AbsenceRecord(
        absence_id="ABS-004",
        employee_id="E1001",
        employee_display_name="Sara Bennani",
        absence_type="Annual Leave",
        start_date=date(2026, 3, 28),
        end_date=date(2026, 3, 29),
        days=1.5,
    ),
    AbsenceRecord(
        absence_id="ABS-005",
        employee_id="E1002",
        employee_display_name="Ahmed El Idrissi",
        absence_type="Sick Leave",
        start_date=date(2026, 3, 11),
        end_date=date(2026, 3, 11),
        days=1.0,
    ),
    AbsenceRecord(
        absence_id="ABS-006",
        employee_id="E1002",
        employee_display_name="Ahmed El Idrissi",
        absence_type="Annual Leave",
        start_date=date(2026, 3, 25),
        end_date=date(2026, 3, 26),
        days=2.0,
    ),
    AbsenceRecord(
        absence_id="ABS-007",
        employee_id="E1003",
        employee_display_name="Yasmine Alami",
        absence_type="Annual Leave",
        start_date=date(2026, 2, 9),
        end_date=date(2026, 2, 10),
        days=2.0,
    ),
    AbsenceRecord(
        absence_id="ABS-008",
        employee_id="E1003",
        employee_display_name="Yasmine Alami",
        absence_type="Medical Appointment",
        start_date=date(2026, 2, 17),
        end_date=date(2026, 2, 17),
        days=0.5,
    ),
    AbsenceRecord(
        absence_id="ABS-009",
        employee_id="E1003",
        employee_display_name="Yasmine Alami",
        absence_type="Annual Leave",
        start_date=date(2026, 4, 2),
        end_date=date(2026, 4, 3),
        days=2.0,
    ),
    AbsenceRecord(
        absence_id="ABS-010",
        employee_id="E1005",
        employee_display_name="Karim Ouali",
        absence_type="Unpaid Leave",
        start_date=date(2026, 3, 8),
        end_date=date(2026, 3, 8),
        days=1.0,
    ),
    AbsenceRecord(
        absence_id="ABS-011",
        employee_id="E1006",
        employee_display_name="Yasmine Amrani",
        absence_type="Annual Leave",
        start_date=date(2026, 2, 20),
        end_date=date(2026, 2, 21),
        days=2.0,
    ),
]

DEMO_USERS: list[DemoUserSummary] = [
    DemoUserSummary(
        user_id="demo_employee_sara",
        display_name="Sara Bennani",
        role="employee",
        employee_id="E1001",
        description="Employee demo user who can view only Sara's own data.",
    ),
    DemoUserSummary(
        user_id="demo_manager_meryem",
        display_name="Meryem Ait Said",
        role="manager",
        employee_id="E1000",
        description="Manager demo user with access to self and direct reports Sara, Ahmed, and Yasmine Alami.",
    ),
    DemoUserSummary(
        user_id="demo_manager_omar",
        display_name="Omar Kabbaj",
        role="manager",
        employee_id="E1004",
        description="Manager demo user with access to self, Karim Ouali, and Yasmine Amrani.",
    ),
    DemoUserSummary(
        user_id="demo_hr_admin_nadia",
        display_name="Nadia El Fassi",
        role="hr_admin",
        employee_id="E9000",
        description="HR admin demo user with access to all seeded employees.",
    ),
]

DEMO_ACCESS_MAP: dict[str, list[str]] = {
    "demo_employee_sara": ["E1001"],
    "demo_manager_meryem": ["E1000", "E1001", "E1002", "E1003"],
    "demo_manager_omar": ["E1004", "E1005", "E1006"],
    "demo_hr_admin_nadia": [employee.employee_id for employee in MOCK_EMPLOYEES],
}
